name: Check PR to main for blocking comments

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - review_requested
      - synchronize
    branches:
      - main

jobs:
  pullrequest_to_main:
    runs-on: ubuntu-latest

    steps:
      # get changed files from PR
      - name: Checkout PR head ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: files/**
      - name: Print Changed Files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
        run: |
          echo "Changed files:"
          cat $ALL_CHANGED_FILES
